assert(type(TF2_API_VERSION) == "string" and TF2_API_VERSION:match("^1%."), "Update the TF2 Lua host")
local info = tf2.info()
local caps = tf2.capabilities()
print(info.game, info.game_id, info.api_version)
print("Four teams:", caps.four_teams, "Civilian:", caps.civilian)
print("Game data available:", tf2.session().data_available)
