const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
  const {createRadarServer}=await import('../relay/server.mjs');
  const root=path.resolve(__dirname,'..');
  const output=path.resolve(root,'../build/web-radar-validation');fs.mkdirSync(output,{recursive:true});
  const app=createRadarServer({root});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));
  const origin=`http://127.0.0.1:${app.server.address().port}`,id='1234567890abcdef1234567890abcdef',token='9'.repeat(64);
  const endpoint=`${origin}/web-radar/api/session/${id}`;
  let seq=0,timer;
  const names=['Ferris','Vox','Opie','Pines','Host','Greymouth','Yanni','Dayo','Frank','Uri'];
  const positions=[[-1560,690],[-1010,-680],[-470,-1920],[-1780,-2010],[-2050,-860],[850,-1000],[300,-2100],[-880,-2020],[-1920,190],[-950,510]];
  const entity=(id,kind,x,y)=>({id,kind,team:0,x,y,z:0,yaw:45,health:100,armor:100,money:3250,weapon:7,grenade:0,radius:0,timer:-1,alive:true,local:false,bomb:false,defusing:false,name:''});
  let entities=names.map((name,i)=>({...entity(i+1,0,...positions[i]),name:`${name} [TEST]`,team:i<5?2:3,local:i===4,health:i===8?0:100-i*3,alive:i!==8,weapon:[7,9,40,16,60][i%5],bomb:i===2}));
  entities.forEach((e,i)=>{e.steamId=i===9?'':String(76561198012345679n+BigInt(i));});
  const uploads=entities.filter(e=>e.steamId).map((e,i)=>{
    const pixels=Buffer.alloc(4096);
    for(let y=0;y<32;++y)for(let x=0;x<32;++x){const n=(y*32+x)*4,on=(x>8&&x<24&&y>6&&y<19)||(y>23&&x>4&&x<28);
      pixels[n]=on?210:45+i*9;pixels[n+1]=on?188:55+i*7;pixels[n+2]=on?115:75+i*13;pixels[n+3]=255;}
    return {steamId:e.steamId,rgba:pixels.toString('base64')};
  });
  let avatarCursor=0;
  entities.push({...entity(10000,1,-410,-2160),timer:25.6,defusing:true}, {...entity(100,3,-1140,-1190),radius:144}, {...entity(101,4,-370,-1630),radius:120}, {...entity(102,6,-1650,-320),weapon:9}, {...entity(103,5,-550,-720),grenade:2}, {...entity(104,7,-720,480)});
  let current={version:1,state:'live',keepLink:true,map:'de_mirage',layer:'de_mirage',calibration:{x:-3230,y:1713,scale:5,size:1024,offsetX:0,offsetY:0,zoom:1},entities};
  const send=async(method='POST')=>{const res=await fetch(endpoint,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:method==='DELETE'?undefined:JSON.stringify({...current,seq:++seq,avatars:current.state==='live'?uploads.slice(avatarCursor,avatarCursor+2):[]})});assert.equal(res.status,204);if(current.state==='live')avatarCursor+=2;else avatarCursor=0;};
  const browser=await chromium.launch({channel:'msedge',headless:true});
  const errors=[];
  try{
    await send('PUT');
    timer=setInterval(()=>send().catch(e=>errors.push(e.message)),150);
    const context=await browser.newContext({viewport:{width:1600,height:1050},permissions:['clipboard-read','clipboard-write'],reducedMotion:'reduce'});
    await context.route('https://steamcommunity.com/**',route=>route.fulfill({contentType:'text/html',body:'<title>Steam profile navigation fixture</title>'}));
    const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
    await page.goto(`${origin}/web-radar/${id}`);
    await page.waitForFunction(()=>document.querySelector('#status').textContent==='Live');
    await page.waitForFunction(()=>document.querySelectorAll('.player').length===10);
    await page.waitForFunction(()=>performance.getEntriesByType('resource').some(r=>r.name.endsWith('/maps/de_mirage.png')));
    await page.waitForFunction(()=>document.querySelectorAll('.steam-avatar:not([hidden])').length===9);
    assert.equal(await page.locator('.avatar-fallback:not([hidden])').count(),1);
    assert.equal(await page.locator('.player-profile[href]').count(),9);
    assert.equal(await page.locator('.player-profile:not([href])').count(),1);
    assert.equal(await page.locator('.player-profile').first().getAttribute('href'),'https://steamcommunity.com/profiles/76561198012345679/');
    await page.locator('.player-profile').first().focus();
    current.entities[0].health=93;
    await page.waitForFunction(()=>document.querySelector('.hp').textContent==='93 HP');
    assert.equal(await page.evaluate(()=>document.activeElement===document.querySelector('.player-profile')),true);
    const popupReady=page.waitForEvent('popup');await page.keyboard.press('Enter');const popup=await popupReady;
    await popup.waitForLoadState();assert.equal(popup.url(),'https://steamcommunity.com/profiles/76561198012345679/');
    assert.equal(await popup.evaluate(()=>window.opener),null);await popup.close();
    // Broken images retain the avatar fallback and working profile action.
    await page.locator('.steam-avatar').first().evaluate(img=>img.src='data:image/png;base64,broken');
    await page.waitForFunction(()=>document.querySelector('.steam-avatar').hidden&&!document.querySelector('.avatar-fallback').hasAttribute('hidden'));
    await page.locator('.steam-avatar').first().evaluate(img=>img.src=img.dataset.image);
    await page.waitForFunction(()=>!document.querySelector('.steam-avatar').hidden);
    await page.locator('.player-profile').first().blur();
    await page.screenshot({path:path.join(output,'desktop-synthetic.png'),fullPage:true});
    await page.getByRole('button',{name:'Copy link',exact:true}).click();
    assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),`${origin}/web-radar/${id}`);
    await page.locator('#drops').uncheck();await page.locator('#utility').uncheck();await page.locator('#names').uncheck();
    await page.locator('#drops').check();await page.locator('#utility').check();await page.locator('#names').check();
    current.entities[0].name='<img src=x onerror=alert(1)>';
    await page.waitForFunction(()=>document.querySelector('.player-name').textContent.includes('<img'));
    assert.equal(await page.locator('.roster img').count(),10);
    assert.equal(await page.locator('.roster img:not(.steam-avatar)').count(),0);
    current.entities[0].name='Ferris [TEST]';
    await page.waitForFunction(()=>document.querySelector('.player-name').textContent==='Ferris [TEST]');
    for(const [name,width,height] of [['phone',375,812],['landscape',812,375]]){
      await page.setViewportSize({width,height});
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${name} overflow`);
      await page.screenshot({path:path.join(output,`${name}-synthetic.png`),fullPage:true});
    }
    await page.setViewportSize({width:1440,height:1000});
    current.entities[0].steamId='76561198012345699';
    await page.waitForFunction(()=>document.querySelector('.player-profile').href.endsWith('/76561198012345699/'));
    assert.equal(await page.locator('.steam-avatar').first().isVisible(),false);
    current.entities[0].steamId=uploads[0].steamId;avatarCursor=0;
    await page.waitForFunction(()=>document.querySelector('.player-profile').href.endsWith('/76561198012345679/')&&!document.querySelector('.steam-avatar').hidden);
    current={...current,map:'de_nuke',layer:'de_nuke_lower'};
    await page.waitForFunction(()=>document.querySelector('#map-name').textContent==='Nuke');
    await page.locator('#floor').selectOption('upper');assert.equal(await page.locator('#floor').inputValue(),'upper');
    await page.locator('#floor').selectOption('auto');
    current={...current,state:'waiting',map:'',layer:'',entities:[]};
    await page.waitForFunction(()=>document.querySelector('#state-title').textContent==='Waiting for the next match');
    assert.equal(await page.locator('.player').count(),0);
    await page.screenshot({path:path.join(output,'waiting.png')});
    current={...current,state:'live',map:'de_mirage',layer:'de_mirage',entities};
    await page.waitForFunction(()=>document.querySelector('#status').textContent==='Live');
    await page.waitForFunction(()=>document.querySelectorAll('.steam-avatar:not([hidden])').length===9);
    clearInterval(timer);timer=null;
    await page.waitForFunction(()=>document.querySelector('#status').textContent==='Reconnecting');
    assert.equal(await page.locator('.player').count(),0);
    await send();await page.waitForFunction(()=>document.querySelector('#status').textContent==='Live');
    await send('DELETE');await page.waitForFunction(()=>document.querySelector('#status').textContent==='Ended');
    assert.equal(await page.locator('.player').count(),0);
    await page.screenshot({path:path.join(output,'ended.png')});
    await page.goto(`${origin}/web-radar/${'a'.repeat(32)}`);await page.waitForFunction(()=>document.querySelector('#status').textContent==='Ended');
    await page.goto(`${origin}/web-radar/`);assert.equal(await page.locator('#state-title').textContent(),'Follow a match');
    assert.deepEqual(errors,[]);
    fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({passed:true,synthetic:true,errors,checks:['live SSE','10-player roster','copy URL','filters','XSS text escaping','Steam avatar pixels','exact profile URL/new tab','noopener','keyboard focus preserved','bot fallback','broken image fallback','slot identity changes clear old avatars','avatars restored after match transition','375px mobile','812px landscape','reduced motion','map and floor changes','waiting clears entities','host loss clears entities','reconnect','Stop','expired link','landing']},null,2));
    console.log('Web Radar browser checks passed (synthetic fixtures)');
  }finally{if(timer)clearInterval(timer);await browser.close();app.closeAll();app.server.closeAllConnections();app.server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
