'use strict';
function anchorLayer(l){const s=settings(),[w,h]=dimensions(),side=Math.min(w,h)*Number(s.scale)/100,a=-Number(s.rotation)*Math.PI/180,dx=l.x*w/100-w*Number(s.logoX)/100,dy=l.y*h/100-h*Number(s.logoY)/100;l.anchor={x:(dx*Math.cos(a)-dy*Math.sin(a))/side,y:(dx*Math.sin(a)+dy*Math.cos(a))/side,size:Math.min(w,h)*l.size/100/side,rotation:l.rotation-Number(s.rotation)};}
function syncAttached(l){if(!l.anchor)return;const s=settings(),[w,h]=dimensions(),side=Math.min(w,h)*Number(s.scale)/100,a=Number(s.rotation)*Math.PI/180,{x,y,size,rotation}=l.anchor;l.x=(w*Number(s.logoX)/100+side*(x*Math.cos(a)-y*Math.sin(a)))/w*100;l.y=(h*Number(s.logoY)/100+side*(x*Math.sin(a)+y*Math.cos(a)))/h*100;l.size=size*Number(s.scale);l.rotation=rotation+Number(s.rotation);}
function attachmentGeometry(l){const factor=l.anchor.size/Math.max(l.img.width,l.img.height);return{x:l.anchor.x,y:l.anchor.y,w:l.img.width*factor,h:l.img.height*factor};}
const oldGeometry=layerGeometry;layerGeometry=function(l,w,h){syncAttached(l);return oldGeometry(l,w,h);};
const looseDraw=drawLayers;drawLayers=function(c,w,h){const s=settings(),t=paused?pausedAt:performance.now()-started,m=motion(t,s);for(const l of layers){if(!l.anchor){const g=oldGeometry(l,w,h);c.save();c.translate(g.x,g.y);c.rotate(l.rotation*Math.PI/180);c.globalAlpha=l.opacity;c.drawImage(l.img,-g.w/2,-g.h/2,g.w,g.h);c.restore();continue;}const g=attachmentGeometry(l),side=Math.min(w,h)*Number(s.scale)/100*m.zoom;c.save();c.translate(w*Number(s.logoX)/100+m.x*h/1024,h*Number(s.logoY)/100+m.y*h/1024);c.rotate(m.rotation*Math.PI/180);c.transform(1,0,Math.tan(m.skew*Math.PI/180),1,0,0);c.scale(m.sx,m.sy);c.rotate(Number(s.rotation)*Math.PI/180);c.scale(side,side);c.translate(g.x,g.y);c.rotate(l.anchor.rotation*Math.PI/180);c.globalAlpha=l.opacity*m.opacity;c.drawImage(l.img,-g.w/2,-g.h/2,g.w,g.h);c.restore();}};
// SVG attachment markup sits inside the same animated transform as the base logo.
const attachedSVG=buildSVG;buildSVG=function(){const saved=layers;let svg;try{layers=saved.filter(l=>!l.anchor);svg=attachedSVG();}finally{layers=saved;}const s=settings(),[w,h]=dimensions(),side=Math.min(w,h)*Number(s.scale)/100;const markup=saved.filter(l=>l.anchor).map(l=>{const g=attachmentGeometry(l);return '<g opacity="'+l.opacity+'" transform="translate('+g.x*side+' '+g.y*side+') rotate('+l.anchor.rotation+')"><image width="'+g.w*side+'" height="'+g.h*side+'" x="'+(-g.w*side/2)+'" y="'+(-g.h*side/2)+'" href="'+l.data+'"/></g>';}).join('');const img=/<image (?:filter="url\(#surface\)" )?x="[^>]+(?:\/>|><animate[^>]+\/><\/image>)/;return svg.replace(img,match=>match+markup);};
const attachButton=document.createElement('button');attachButton.id='attachLogo';$('layerTools').prepend(attachButton);
const attachHint=document.createElement('p');attachHint.className='hint';attachHint.textContent='Attached accessories follow the base logo’s position, size and animation. Pause motion to adjust their placement.';attachButton.after(attachHint);
function editingPose(){paused=true;pausedAt=0;$('pause').textContent='Resume motion';$('pause').setAttribute('aria-pressed','true');}
const attachmentRefresh=refreshLayers;refreshLayers=function(){layers.forEach(syncAttached);attachmentRefresh();attachButton.textContent=layers[selected]?.anchor?'Detach from logo':'Attach to logo';document.querySelectorAll('#layerList button').forEach((b,i)=>{const l=layers[layers.length-1-i];if(l.anchor)b.textContent+=' · attached';});};
attachButton.onclick=()=>{const l=layers[selected];if(!l)return;checkpoint();if(l.anchor){syncAttached(l);delete l.anchor;status('Layer detached.');}else{anchorLayer(l);editingPose();status('Attached to Scooby. Position it, then resume motion to animate them together.');}refreshLayers();};
const attachmentAdd=addLayer;addLayer=async function(data,name,x=50,y=50){const count=layers.length;await attachmentAdd(data,name,x,y);if(layers.length>count&&name.startsWith('Accessories /')){anchorLayer(layers[selected]);editingPose();refreshLayers();status('Accessory attached to Scooby. Drag it into place, then resume motion.');}};
const oldPointerDown=stage.onpointerdown,oldPointerMove=stage.onpointermove;stage.onpointerdown=e=>{if(layers.some(l=>l.anchor))editingPose();layers.forEach(syncAttached);oldPointerDown(e);};stage.onpointermove=e=>{const l=layers[selected],anchor=l?.anchor;if(anchor)delete l.anchor;oldPointerMove(e);if(anchor){if(drag)anchorLayer(l);else l.anchor=anchor;}};
for(const id of ['layerSize','layerRotation','layerOpacity']){const prev=$(id).oninput;$(id).oninput=e=>{prev(e);const l=layers[selected];if(l?.anchor)anchorLayer(l);};}
const duplicate=$('duplicateLayer').onclick;$('duplicateLayer').onclick=()=>{duplicate();const l=layers[selected];if(l?.anchor){l.anchor={...l.anchor,x:l.anchor.x+.05,y:l.anchor.y+.05};refreshLayers();}};
// Merge free layers without destroying attachments.
const merge=$('mergeLayers').onclick;$('mergeLayers').onclick=async()=>{if(layers.some(l=>l.anchor)){status('Attached accessories already move as one logo. Detach them first if you want to flatten the layers.');return;}await merge();};
refreshLayers();
