'use strict';
const $=id=>document.getElementById(id);
const keys=['depth','sidecolor','textFinish','finish','gloss','glow','surfaceMotion','format','width','height','layout','bgcolor2','logoX','logoY','textX','textY','textSize','subtitle','logo','paint','target','color1','color2','angle','scale','rotation','background','bgcolor','caption','textcolor','motion','duration','resolution'];
const defaults={depth:'9',sidecolor:'#6634c4',textFinish:'normal',finish:'flat',gloss:'65',glow:'0',surfaceMotion:'none',format:'square',width:'1500',height:'500',layout:'center',bgcolor2:'#44316e',logoX:'50',logoY:'50',textX:'50',textY:'90',textSize:'6',subtitle:'',paint:'original',target:'white',color1:'#aa7cff',color2:'#57e5ed',angle:'135',scale:'82',rotation:'0',background:'transparent',bgcolor:'#14121d',caption:'',textcolor:'#ffffff',motion:'none',duration:'4',resolution:'1024'};
const assets=window.SCOOBY_ASSETS;let source=new Image(),sourceData='',ready=false,paused=false,started=performance.now(),pausedAt=0,loadId=0;
let fadePoints=[1,.35,.8,.2,.65,1];
const stage=$('preview'),ctx=stage.getContext('2d'),art=document.createElement('canvas');art.width=art.height=1024;const ac=art.getContext('2d');
for(const a of assets){const option=document.createElement('option');option.value=a.file;option.textContent=a.file.replace(/\.png$/i,'').replaceAll('/',' / ');$('logo').append(option);}
$('logo').value=assets.find(a=>a.file==='Originals/scooby-logo-nobg.png')?.file||assets[0].file;
function settings(){return Object.fromEntries(keys.map(k=>[k,$(k).value]));}
function status(s){$('status').textContent=s;}
async function loadImage(data){const id=++loadId;const img=new Image();img.src=data;try{await img.decode();if(id!==loadId)return;source=img;sourceData=data;ready=true;rebuild();}catch{status('This image could not be opened. Try a PNG or WebP.');}}
function loadSelected(){const a=assets.find(a=>a.file===$('logo').value);if(a)loadImage(a.data);}
function rebuild(){if(!ready)return;const s=settings();ac.clearRect(0,0,1024,1024);const ratio=Math.min(1024/source.width,1024/source.height);ac.drawImage(source,(1024-source.width*ratio)/2,(1024-source.height*ratio)/2,source.width*ratio,source.height*ratio);
 if(s.paint!=='original'){const pixels=ac.getImageData(0,0,1024,1024);const mask=document.createElement('canvas');mask.width=mask.height=1024;const mc=mask.getContext('2d');const m=mc.createImageData(1024,1024);for(let i=0;i<pixels.data.length;i+=4){const d=pixels.data;const min=Math.min(d[i],d[i+1],d[i+2]),max=Math.max(d[i],d[i+1],d[i+2]);const amount=s.target==='all'?1:Math.min(1,Math.max(0,(min-130)/85))*Math.max(0,1-(max-min)/65);m.data[i]=m.data[i+1]=m.data[i+2]=255;m.data[i+3]=d[i+3]*amount;}mc.putImageData(m,0,0);mc.globalCompositeOperation='source-in';let paint=s.color1;if(s.paint==='gradient'){const a=Number(s.angle)*Math.PI/180;paint=mc.createLinearGradient(512-Math.cos(a)*512,512-Math.sin(a)*512,512+Math.cos(a)*512,512+Math.sin(a)*512);paint.addColorStop(0,s.color1);paint.addColorStop(1,s.color2);}mc.fillStyle=paint;mc.fillRect(0,0,1024,1024);if(s.target==='all')ac.clearRect(0,0,1024,1024);ac.drawImage(mask,0,0);}
 $('angleValue').value=s.angle+'°';$('rotationValue').value=s.rotation+'°';$('scaleValue').value=s.scale+'%';$('durationValue').value=s.duration+'s';}
function motion(t,s){const phase=(t/(Number(s.duration)*1000))%1;let opacity=1,zoom=1,y=0,rotation=0;if(s.motion==='fade')opacity=.3+.7*(.5+.5*Math.cos(phase*Math.PI*2));if(s.motion==='random'){const f=phase*(fadePoints.length-1),i=Math.floor(f);opacity=fadePoints[i]+(fadePoints[i+1]-fadePoints[i])*(f-i);}if(s.motion==='pulse')zoom=.94+.06*(.5+.5*Math.cos(phase*Math.PI*2));if(s.motion==='float')y=Math.sin(phase*Math.PI*2)*18;if(s.motion==='spin')rotation=phase*360;let x=0,sx=1,sy=1,skew=0;const a=phase*Math.PI*2;
if(s.motion==='extruded'){sx=Math.cos(a);if(Math.abs(sx)<.025)sx=sx<0?-.025:.025;}
if(s.motion==='spin3d'){sx=Math.cos(a);skew=10*Math.sin(a);}
if(s.motion==='flip3d'){sy=Math.cos(a);skew=8*Math.sin(a);}
if(s.motion==='tumble'){sx=Math.cos(a);sy=.85+.15*Math.cos(a);rotation=phase*360;skew=12*Math.sin(a);}
if(s.motion==='tilt'){sx=.88+.12*Math.cos(a);sy=.95+.05*Math.cos(a);skew=16*Math.sin(a);rotation=5*Math.sin(a);}
if(s.motion==='wobble'){rotation=12*Math.sin(a);zoom=.96+.04*Math.cos(a*2);}
if(s.motion==='bounce'){y=-55*(1-Math.cos(a))/2;sy=1-.08*Math.pow(Math.max(0,Math.cos(a)),8);}
if(s.motion==='orbit'){x=35*Math.cos(a);y=22*Math.sin(a);}
if(s.motion==='swing')rotation=22*Math.sin(a);
if(s.motion==='zoom')zoom=.72+.28*(.5+.5*Math.cos(a));
return{opacity,zoom,y,rotation,x,sx,sy,skew};}
function dimensions(s=settings()){const presets={youtubeBanner:[2560,1440],youtubeLogo:[800,800],youtubeThumbnail:[1280,720],discordProfile:[680,240],discordServer:[960,540],discordLogo:[512,512],emoji128:[128,128],emoji64:[64,64],emoji32:[32,32],sticker:[320,320],square:[+s.resolution,+s.resolution],banner:[1500,500],cover:[1920,640],video:[1920,1080],portrait:[1080,1920]};return presets[s.format]||[Math.max(128,Math.min(4096,+s.width||1500)),Math.max(128,Math.min(4096,+s.height||500))].map(Math.round);}
function backdrop(c,w,h,s){if(s.background==='transparent')return;let fill=s.bgcolor;if(s.background==='gradient'){fill=c.createLinearGradient(0,0,w,h);fill.addColorStop(0,s.bgcolor);fill.addColorStop(1,s.bgcolor2);}c.fillStyle=fill;c.fillRect(0,0,w,h);}
function textLayer(c,w,h,s){const x=w*Number(s.textX)/100,y=h*Number(s.textY)/100;const align=s.layout==='left'?'left':s.layout==='right'?'right':'center';const maxWidth=Math.max(20,align==='left'?w-x-w*.04:align==='right'?x-w*.04:Math.min(x,w-x)*1.9);c.save();c.textAlign=align;c.fillStyle=s.textcolor;const size=Math.min(w,h)*Number(s.textSize)/100;c.font='700 '+size+'px Arial,sans-serif';if(s.caption)c.fillText(s.caption,x,y,maxWidth);c.font='400 '+size*.43+'px Arial,sans-serif';c.globalAlpha=.78;if(s.subtitle)c.fillText(s.subtitle,x,y+size*.85,maxWidth);c.restore();}
function draw(target,width,t,height){const s=settings(),dims=dimensions(s),h=height||width*dims[1]/dims[0],m=motion(t,s);target.clearRect(0,0,width,h);backdrop(target,width,h,s);const side=Math.min(width,h)*Number(s.scale)/100*m.zoom;target.save();target.translate(width*Number(s.logoX)/100+m.x*h/1024,h*Number(s.logoY)/100+m.y*h/1024);target.rotate(m.rotation*Math.PI/180);target.transform(1,0,Math.tan(m.skew*Math.PI/180),1,0,0);if(s.motion==='extruded'&&typeof drawExtrusion==='function')drawExtrusion(target,side,t,s);target.scale(m.sx,m.sy);target.rotate(Number(s.rotation)*Math.PI/180);target.globalAlpha=m.opacity;target.drawImage(art,-side/2,-side/2,side,side);target.restore();textLayer(target,width,h,s);}
function tick(now){if(ready){const [w,h]=dimensions();const ph=Math.round(1024*h/w);if(stage.height!==ph)stage.height=ph;stage.parentElement.style.maxWidth=Math.min(850,innerHeight*.65*w/h)+'px';draw(ctx,1024,paused?pausedAt:now-started,ph);}requestAnimationFrame(tick);}requestAnimationFrame(tick);
for(const key of keys)$(key).addEventListener('input',()=>{if(key==='logo')loadSelected();else {if(key==='layout'){const side=$('layout').value;$('logoX').value=side==='left'?'23':side==='right'?'77':'50';$('logoY').value='50';$('textX').value=side==='left'?'47':side==='right'?'53':'50';$('textY').value=side==='center'?'88':'47';}rebuild();}});
document.querySelectorAll('[data-colors]').forEach(b=>b.addEventListener('click',()=>{[$('color1').value,$('color2').value]=b.dataset.colors.split(',');$('paint').value='gradient';rebuild();}));
$('shuffle').onclick=()=>{fadePoints=[1,...Array.from({length:6},()=>.15+Math.random()*.85),1];$('motion').value='random';started=performance.now();status('New random fading pattern applied.');};
$('pause').onclick=()=>{if(!paused)pausedAt=performance.now()-started;else started=performance.now()-pausedAt;paused=!paused;$('pause').textContent=paused?'Resume motion':'Pause motion';$('pause').setAttribute('aria-pressed',String(paused));};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
$('png').onclick=()=>{if(!ready)return;const c=document.createElement('canvas');[c.width,c.height]=dimensions();draw(c.getContext('2d'),c.width,paused?pausedAt:performance.now()-started,c.height);c.toBlob(blob=>{if(blob)download(blob,'scooby-custom.png');},'image/png');status('PNG exported at '+c.width+' × '+c.height+'.');};
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function buildSVG(){const s=settings(),[w,h]=dimensions(),dur=s.duration+'s',side=Math.min(w,h)*Number(s.scale)/100;let opacity='',transform='';if(s.motion==='fade'||s.motion==='random')opacity='<animate attributeName="opacity" values="'+(s.motion==='fade'?'1;.3;1':fadePoints.join(';'))+'" dur="'+dur+'" repeatCount="indefinite"/>';if(s.motion==='pulse')transform='<animateTransform attributeName="transform" type="scale" values="1;.94;1" dur="'+dur+'" repeatCount="indefinite"/>';if(s.motion==='float')transform='<animateTransform attributeName="transform" type="translate" values="0 0;0 '+(18*h/1024)+';0 0;0 '+(-18*h/1024)+';0 0" dur="'+dur+'" repeatCount="indefinite"/>';if(s.motion==='spin')transform='<animateTransform attributeName="transform" type="rotate" from="0" to="360" dur="'+dur+'" repeatCount="indefinite"/>';const extra=['extruded','spin3d','flip3d','tumble','tilt','wobble','bounce','orbit','swing','zoom'].includes(s.motion);let closeMotion='';if(extra){const samples=Array.from({length:65},(_,i)=>motion(i/64*Number(s.duration)*1000,s));if(s.motion==='tumble')samples[64].rotation=360;const anim=(type,values)=>'<animateTransform attributeName="transform" type="'+type+'" values="'+values.join(';')+'" dur="'+dur+'" repeatCount="indefinite"/>';transform=anim('translate',samples.map(m=>(m.x*h/1024)+' '+(m.y*h/1024)))+'<g>'+anim('rotate',samples.map(m=>m.rotation))+'<g>'+anim('skewX',samples.map(m=>m.skew))+'<g>'+anim('scale',samples.map(m=>(m.sx*m.zoom)+' '+(m.sy*m.zoom)));closeMotion='</g></g></g>';}
const layer=document.createElement('canvas');layer.width=w;layer.height=h;const lc=layer.getContext('2d');backdrop(lc,w,h,s);const bg=layer.toDataURL();lc.clearRect(0,0,w,h);textLayer(lc,w,h,s);const text=layer.toDataURL();return '<svg xmlns="http://www.w3.org/2000/svg" width="'+w+'" height="'+h+'" viewBox="0 0 '+w+' '+h+'"><title>Custom Scooby artwork</title><image width="'+w+'" height="'+h+'" href="'+bg+'"/><g transform="translate('+w*Number(s.logoX)/100+' '+h*Number(s.logoY)/100+')">'+(typeof extrusionSVG==='function'?extrusionSVG(s,side):'')+'<g>'+transform+'<g transform="rotate('+s.rotation+')">'+opacity+'<image x="'+(-side/2)+'" y="'+(-side/2)+'" width="'+side+'" height="'+side+'" href="'+art.toDataURL()+'"/></g>'+closeMotion+'</g></g><image width="'+w+'" height="'+h+'" href="'+text+'"/></svg>';}
$('svg').onclick=()=>{if(!ready)return;download(new Blob([buildSVG()],{type:'image/svg+xml'}),'scooby-custom.svg');status('Self-contained SVG exported'+($('motion').value==='none'?'.':' with animation.'));};
$('save').onclick=()=>{download(new Blob([JSON.stringify({version:1,settings:settings(),image:sourceData,fadePoints},null,2)],{type:'application/json'}),'scooby-design.json');status('Design saved. Use Load design to edit it later.');};
$('upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){status('Choose an image smaller than 20 MB.');return;}const reader=new FileReader();reader.onload=()=>{loadImage(reader.result);status('Custom image loaded.');};reader.readAsDataURL(file);};
$('load').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>150*1024*1024)throw Error();const d=JSON.parse(await file.text());if(d.version!==1||!d.settings||!/^data:image\/(png|webp|jpeg);base64,/.test(d.image))throw Error();for(const key of keys){const value=String(d.settings[key]??defaults[key]??$('logo').value),el=$(key);if(el.tagName==='SELECT'&&![...el.options].some(o=>o.value===value))continue;el.value=value;}if(Array.isArray(d.fadePoints)&&d.fadePoints.length>=2&&d.fadePoints.length<=30&&d.fadePoints.every(n=>Number.isFinite(n)&&n>=0&&n<=1))fadePoints=d.fadePoints;await loadImage(d.image);status('Saved design loaded.');}catch{status('Could not load this design. Choose a Scooby Studio JSON file.');}};
$('reset').onclick=()=>{for(const [k,v] of Object.entries(defaults))$(k).value=v;loadSelected();started=performance.now();status('Settings reset.');};
loadSelected();

$('bannerPreset').onclick=()=>{$('format').value='banner';$('layout').value='left';$('logoX').value='23';$('logoY').value='50';$('textX').value='47';$('textY').value='47';$('textSize').value='15';$('background').value='gradient';$('caption').value='SCOOBY';$('subtitle').value='MAKE IT YOURS';rebuild();status('Banner ready — customize the title, colors and logo.');};
