'use strict';
const rawArt=document.createElement('canvas');rawArt.width=rawArt.height=1024;
const baseRebuild=rebuild;
rebuild=function(){baseRebuild();if(ready){const c=rawArt.getContext('2d');c.clearRect(0,0,1024,1024);c.drawImage(art,0,0);applyFinish(0);}};
function applyFinish(t){const s=settings(),cycle=t/(Number(s.duration)*1000),strength=Number(s.gloss)/100;ac.clearRect(0,0,1024,1024);ac.save();if(['color','both'].includes(s.surfaceMotion))ac.filter='hue-rotate('+(Math.sin(cycle*Math.PI*2)*75)+'deg)';ac.drawImage(rawArt,0,0);ac.restore();if(s.finish!=='flat'){const coat=document.createElement('canvas');coat.width=coat.height=1024;const c=coat.getContext('2d');c.drawImage(rawArt,0,0);c.globalCompositeOperation='source-in';const g=c.createLinearGradient(0,0,230,1024);if(s.finish==='chrome'){g.addColorStop(0,'#f9fbff');g.addColorStop(.28,'#c9ccd8');g.addColorStop(.46,'#ffffff');g.addColorStop(.52,'#666579');g.addColorStop(.72,'#dddfe9');g.addColorStop(1,'#858394');}else{g.addColorStop(0,'rgba(255,255,255,'+strength+')');g.addColorStop(.28,'rgba(255,255,255,0)');g.addColorStop(.49,'rgba(255,255,255,'+strength*.48+')');g.addColorStop(.51,'rgba(20,0,60,'+strength*.6+')');g.addColorStop(.78,'rgba(255,255,255,0)');g.addColorStop(1,'rgba(255,255,255,'+strength*.8+')');}c.fillStyle=g;c.fillRect(0,0,1024,1024);ac.drawImage(coat,0,0);}
if(['shine','both'].includes(s.surfaceMotion)){const shine=document.createElement('canvas');shine.width=shine.height=1024;const c=shine.getContext('2d');c.drawImage(rawArt,0,0);c.globalCompositeOperation='source-in';const x=((cycle%1)*1600)-300,g=c.createLinearGradient(x-130,0,x+130,0);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(.5,'rgba(255,255,255,'+strength+')');g.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=g;c.fillRect(0,0,1024,1024);ac.drawImage(shine,0,0);}}
const finishDraw=draw;draw=function(c,w,t,h){applyFinish(t);c.save();if(Number($('glow').value)){c.shadowColor=$('color1').value;c.shadowBlur=Number($('glow').value)*w/1024;}finishDraw(c,w,t,h);c.restore();};
// Export glow and surface motion as native SVG filters over the base artwork.
const finishSVG=buildSVG;buildSVG=function(){applyFinish(0);let svg=finishSVG();const s=settings(),animated=['color','both'].includes(s.surfaceMotion);const filter='<defs><filter id="surface" x="-50%" y="-50%" width="200%" height="200%" color-interpolation-filters="sRGB"><feColorMatrix type="hueRotate" values="0">'+(animated?'<animate attributeName="values" values="0;75;0;-75;0" dur="'+s.duration+'s" repeatCount="indefinite"/>':'')+'</feColorMatrix>'+(Number(s.glow)>0?'<feDropShadow dx="0" dy="0" stdDeviation="'+Number(s.glow)/2+'" flood-color="'+s.color1+'"/>':'')+'</filter></defs>';svg=svg.replace('<title>',filter+'<title>');svg=svg.replace('<image x="', '<image filter="url(#surface)" x="');if(['shine','both'].includes(s.surfaceMotion)){// Animate a masked light sweep, preserving the original silhouette.
const [w,h]=dimensions(),side=Math.min(w,h)*Number(s.scale)/100;const mask='<defs><mask id="logo-shine"><image x="'+(-side/2)+'" y="'+(-side/2)+'" width="'+side+'" height="'+side+'" href="'+rawArt.toDataURL()+'"/></mask><linearGradient id="shine-band"><stop stop-color="white" stop-opacity="0"/><stop offset=".5" stop-color="white" stop-opacity="'+Number(s.gloss)/100+'"/><stop offset="1" stop-color="white" stop-opacity="0"/></linearGradient></defs>';svg=svg.replace('<title>',mask+'<title>');const sweep='<g mask="url(#logo-shine)"><rect x="'+(-side)+'" y="'+(-side/2)+'" width="'+side*.3+'" height="'+side+'" fill="url(#shine-band)"><animate attributeName="x" from="'+(-side)+'" to="'+side+'" dur="'+s.duration+'s" repeatCount="indefinite"/></rect></g>';svg=svg.replace(/<image filter="url\(#surface\)"[^>]+\/>/,match=>match+sweep);}return svg;};
$('glassPreset').onclick=()=>{$('paint').value='gradient';$('target').value='white';$('color1').value='#b625ff';$('color2').value='#3512f5';$('finish').value='glass';$('gloss').value='75';$('glow').value='9';$('surfaceMotion').value='both';$('background').value='color';$('bgcolor').value='#09070f';rebuild();status('Purple glass applied. Adjust highlights, glow and animation to taste.');};
if(ready)rebuild();
