'use strict';
let layers=[],selected=-1,history=[],future=[];
const serialize=()=>layers.map(({img,...l})=>l);
function checkpoint(){history.push(JSON.stringify(serialize()));if(history.length>30)history.shift();future=[];}
async function hydrate(items){return Promise.all(items.map(async l=>{if(!/^data:image\/(png|jpeg|webp);base64,/.test(l.data))throw Error('Unsupported layer');const img=new Image();img.src=l.data;await img.decode();return {...l,name:String(l.name).slice(0,100),x:Math.max(0,Math.min(100,Number(l.x)||0)),y:Math.max(0,Math.min(100,Number(l.y)||0)),size:Math.max(1,Math.min(4000,Number(l.size)||35)),rotation:Number(l.rotation)||0,opacity:Math.max(0,Math.min(1,Number(l.opacity)||0)),img};}));}
function refreshLayers(){const list=$('layerList');list.replaceChildren();layers.forEach((l,i)=>{const b=document.createElement('button');b.textContent=(i===selected?'● ':'')+l.name;b.className=i===selected?'active':'';b.onclick=()=>{selected=i;refreshLayers();};list.prepend(b);});const l=layers[selected];$('layerTools').hidden=!l;if(l){$('layerSize').value=l.size;$('layerRotation').value=l.rotation;$('layerOpacity').value=l.opacity*100;$('layerColor').value=l.tint||'#ffffff';} }
async function addLayer(data,name,x=50,y=50){try{const img=new Image();img.src=data;await img.decode();checkpoint();layers.push({data,name,x,y,size:38,rotation:0,opacity:1,img});selected=layers.length-1;refreshLayers();status('Added '+name+'. Drag it on the canvas or use the layer controls.');}catch{status('Unable to open this image. Use PNG, JPEG or WebP.');}}
function layerGeometry(l,w,h){const max=Math.min(w,h)*l.size/100;const factor=max/Math.max(l.img.width,l.img.height);return {x:w*l.x/100,y:h*l.y/100,w:l.img.width*factor,h:l.img.height*factor};}
function drawLayers(c,w,h){for(const l of layers){const g=layerGeometry(l,w,h);c.save();c.translate(g.x,g.y);c.rotate(l.rotation*Math.PI/180);c.globalAlpha=l.opacity;c.drawImage(l.img,-g.w/2,-g.h/2,g.w,g.h);c.restore();}}
const baseDraw=draw;draw=function(c,w,t,h){const dims=dimensions();h=h||w*dims[1]/dims[0];baseDraw(c,w,t,h);drawLayers(c,w,h);if(c===ctx&&layers[selected]&&(!layers[selected].anchor||paused||settings().motion==='none')){const l=layers[selected],g=layerGeometry(l,w,h);c.save();c.translate(g.x,g.y);c.rotate(l.rotation*Math.PI/180);c.strokeStyle='#d6b4ff';c.lineWidth=2;c.setLineDash([8,5]);c.strokeRect(-g.w/2,-g.h/2,g.w,g.h);c.restore();}};
const baseSVG=buildSVG;buildSVG=function(){const [w,h]=dimensions();const markup=layers.map(l=>{const g=layerGeometry(l,w,h);return '<g opacity="'+l.opacity+'" transform="translate('+g.x+' '+g.y+') rotate('+l.rotation+')"><image x="'+(-g.w/2)+'" y="'+(-g.h/2)+'" width="'+g.w+'" height="'+g.h+'" href="'+l.data+'"/></g>';}).join('');return baseSVG().replace('</svg>',markup+'</svg>');};
const panel=document.createElement('section');panel.className='asset-panel';panel.innerHTML='<h2>Build with layers</h2><p class="hint">Drag assets or image files onto the canvas. Click an asset to add it. Added layers sit above the base logo and text.</p><div class="asset-actions"><label class="import">Add images<input id="layerUpload" type="file" accept="image/png,image/jpeg,image/webp" multiple></label><button id="mergeLayers">Merge added layers</button><button id="undoLayers">Undo layers</button><button id="redoLayers">Redo layers</button></div><label>Asset category<select id="assetCategory"><option value="all">All assets</option><option value="accessories">Hats & accessories</option><option value="logos">Complete logos</option><option value="shapes">Shapes</option></select></label><input id="assetSearch" type="search" placeholder="Search logos, stars, shapes…" aria-label="Search assets"><div id="assetLibrary"></div><h3>Layers · top first</h3><div id="layerList"></div><div id="layerTools" hidden><label>Layer size<input id="layerSize" type="range" min="1" max="500" value="38"></label><label>Layer rotation<input id="layerRotation" type="range" min="-180" max="180" value="0"></label><label>Layer opacity<input id="layerOpacity" type="range" min="0" max="100" value="100"></label><div class="asset-actions"><button id="forward">Bring forward</button><button id="backward">Send backward</button><button id="duplicateLayer">Duplicate</button><button id="deleteLayer">Delete</button></div><label>Recolor layer<input id="layerColor" type="color" value="#ffffff"></label><button id="tintLayer">Apply solid color</button></div>';
document.querySelector('.workspace').append(panel);
const library=[...assets.map(a=>({name:a.file.replace('.png',''),data:a.data}))];
function decoration(name,paint){const c=document.createElement('canvas');c.width=c.height=256;const d=c.getContext('2d');d.strokeStyle=d.fillStyle='#ffffff';d.lineWidth=12;d.lineJoin='round';paint(d);library.push({name:'Shapes / '+name,data:c.toDataURL()});}
for(const count of [4,5,6,8])decoration(count+' point star',c=>{c.beginPath();for(let i=0;i<count*2;i++){const a=i*Math.PI/count-Math.PI/2,r=i%2?42:110;const x=128+Math.cos(a)*r,y=128+Math.sin(a)*r;i?c.lineTo(x,y):c.moveTo(x,y);}c.closePath();c.fill();});
decoration('Ring',c=>{c.beginPath();c.arc(128,128,100,0,Math.PI*2);c.stroke();});
decoration('Circle',c=>{c.beginPath();c.arc(128,128,100,0,Math.PI*2);c.fill();});
decoration('Diamond',c=>{c.beginPath();c.moveTo(128,16);c.lineTo(240,128);c.lineTo(128,240);c.lineTo(16,128);c.closePath();c.stroke();});
decoration('Lightning',c=>{c.beginPath();[[145,8],[44,146],[115,146],[99,248],[216,105],[143,105]].forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.fill();});
decoration('Crown',c=>{c.beginPath();[[28,65],[78,113],[128,30],[178,113],[228,65],[204,215],[52,215]].forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.stroke();});
decoration('Heart',c=>{c.beginPath();c.moveTo(128,220);c.bezierCurveTo(-50,95,60,-10,128,75);c.bezierCurveTo(196,-10,306,95,128,220);c.fill();});
decoration('Shield',c=>{c.beginPath();c.moveTo(128,20);c.lineTo(222,57);c.bezierCurveTo(222,150,190,202,128,240);c.bezierCurveTo(66,202,34,150,34,57);c.closePath();c.stroke();});
decoration('Crosshair',c=>{c.beginPath();c.arc(128,128,65,0,Math.PI*2);c.moveTo(128,12);c.lineTo(128,244);c.moveTo(12,128);c.lineTo(244,128);c.stroke();});
decoration('Stripes',c=>{for(let i=0;i<4;i++)c.fillRect(22,30+i*52,212,17);});
decoration('Corner frame',c=>{for(const [x,y,sx,sy] of [[18,18,1,1],[238,18,-1,1],[18,238,1,-1],[238,238,-1,-1]]){c.beginPath();c.moveTo(x+sx*60,y);c.lineTo(x,y);c.lineTo(x,y+sy*60);c.stroke();}});
function renderLibrary(){const q=$('assetSearch').value.toLowerCase();$('assetLibrary').replaceChildren();library.forEach((a,i)=>{const category=$('assetCategory').value;const accessory=a.name.startsWith('Accessories /'),shape=a.name.startsWith('Shapes /');if(category==='accessories'&&!accessory||category==='shapes'&&!shape||category==='logos'&&(accessory||shape))return;if(!a.name.toLowerCase().includes(q))return;const b=document.createElement('button');b.draggable=true;b.title=a.name;const img=new Image();img.src=a.data;img.alt='';const label=document.createElement('span');label.textContent=a.name.split('/').pop();b.append(img,label);b.onclick=()=>addLayer(a.data,a.name);b.ondragstart=e=>e.dataTransfer.setData('application/x-scooby-asset',String(i));$('assetLibrary').append(b);});}
$('assetCategory').onchange=renderLibrary;$('assetSearch').oninput=renderLibrary;renderLibrary();
async function importFiles(files,x=50,y=50){for(const file of files){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024){status('Use PNG, JPEG or WebP files under 20 MB.');continue;}const data=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file);});await addLayer(data,file.name,x,y);}}
$('layerUpload').onchange=e=>importFiles(e.target.files);
function point(e){const r=stage.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100};}
stage.ondragover=e=>{e.preventDefault();stage.classList.add('drag-over');};stage.ondragleave=()=>stage.classList.remove('drag-over');stage.ondrop=e=>{e.preventDefault();stage.classList.remove('drag-over');const p=point(e),id=e.dataTransfer.getData('application/x-scooby-asset');if(id!==''&&library[Number(id)])addLayer(library[Number(id)].data,library[Number(id)].name,p.x,p.y);else importFiles(e.dataTransfer.files,p.x,p.y);};
let drag=null;stage.onpointerdown=e=>{const p=point(e);const w=stage.width,h=stage.height;selected=-1;for(let i=layers.length-1;i>=0;i--){const l=layers[i],g=layerGeometry(l,w,h),a=-l.rotation*Math.PI/180,dx=p.x*w/100-g.x,dy=p.y*h/100-g.y;const x=dx*Math.cos(a)-dy*Math.sin(a),y=dx*Math.sin(a)+dy*Math.cos(a);if(Math.abs(x)<=g.w/2&&Math.abs(y)<=g.h/2){selected=i;checkpoint();drag={x:p.x-l.x,y:p.y-l.y};stage.setPointerCapture(e.pointerId);break;}}refreshLayers();};stage.onpointermove=e=>{if(!drag||selected<0)return;const p=point(e);layers[selected].x=Math.max(0,Math.min(100,p.x-drag.x));layers[selected].y=Math.max(0,Math.min(100,p.y-drag.y));};stage.onpointerup=stage.onpointercancel=()=>{drag=null;};
for(const [id,key,factor] of [['layerSize','size',1],['layerRotation','rotation',1],['layerOpacity','opacity',.01]]){$(id).onpointerdown=()=>checkpoint();$(id).onkeydown=e=>{if(e.key.startsWith('Arrow'))checkpoint();};$(id).oninput=()=>{if(layers[selected])layers[selected][key]=Number($(id).value)*factor;};}
$('deleteLayer').onclick=()=>{if(selected<0)return;checkpoint();layers.splice(selected,1);selected=layers.length-1;refreshLayers();};
$('duplicateLayer').onclick=()=>{if(selected<0)return;checkpoint();const l=layers[selected];layers.push({...l,x:Math.min(100,l.x+4),y:Math.min(100,l.y+4)});selected=layers.length-1;refreshLayers();};
for(const [id,step] of [['forward',1],['backward',-1]])$(id).onclick=()=>{const next=selected+step;if(selected<0||next<0||next>=layers.length)return;checkpoint();[layers[selected],layers[next]]=[layers[next],layers[selected]];selected=next;refreshLayers();};
$('tintLayer').onclick=async()=>{const l=layers[selected];if(!l)return;checkpoint();const c=document.createElement('canvas');c.width=l.img.width;c.height=l.img.height;const d=c.getContext('2d');d.drawImage(l.img,0,0);d.globalCompositeOperation='source-in';d.fillStyle=$('layerColor').value;d.fillRect(0,0,c.width,c.height);l.data=c.toDataURL();l.img=new Image();l.img.src=l.data;await l.img.decode();l.tint=$('layerColor').value;};
$('mergeLayers').onclick=async()=>{if(layers.length<2){status('Add at least two layers to merge.');return;}const [w,h]=dimensions(),c=document.createElement('canvas');c.width=w;c.height=h;drawLayers(c.getContext('2d'),w,h);const data=c.toDataURL(),img=new Image();img.src=data;await img.decode();checkpoint();layers=[{name:'Merged layers',data,img,x:50,y:50,size:Math.max(w,h)/Math.min(w,h)*100,rotation:0,opacity:1}];selected=0;refreshLayers();status('Added layers merged. Undo layers restores the separate images.');};
for(const [id,from,to] of [['undoLayers',()=>history,()=>future],['redoLayers',()=>future,()=>history]])$(id).onclick=async()=>{if(!from().length)return;to().push(JSON.stringify(serialize()));layers=await hydrate(JSON.parse(from().pop()));selected=layers.length-1;refreshLayers();};
$('save').onclick=()=>{download(new Blob([JSON.stringify({version:1,settings:settings(),image:sourceData,fadePoints,layers:serialize()},null,2)],{type:'application/json'}),'scooby-design.json');status('Design saved with all editable layers.');};
const previousLoad=$('load').onchange;$('load').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>150*1024*1024)throw Error();const d=JSON.parse(await file.text());const loaded=await hydrate(Array.isArray(d.layers)?d.layers:[]);await previousLoad(e);if($('status').textContent==='Saved design loaded.'){layers=loaded;selected=layers.length-1;history=[];future=[];refreshLayers();}}catch{status('Could not load the layers in this design.');}};
