'use strict';
const neonArt=document.createElement('canvas');neonArt.width=neonArt.height=1024;let lightTime=0;
function buildNeon(){const n=neonArt.getContext('2d'),r=rawArt.getContext('2d').getImageData(0,0,1024,1024),out=n.createImageData(1024,1024);for(let y=0;y<1024;y++)for(let x=0;x<1024;x++){const i=(y*1024+x)*4,a=r.data[i+3];if(!a)continue;let min=a;for(const [dx,dy] of [[-3,0],[3,0],[0,-3],[0,3]]){const xx=x+dx,yy=y+dy;min=Math.min(min,xx<0||xx>1023||yy<0||yy>1023?0:r.data[(yy*1024+xx)*4+3]);}const edge=Math.min(1,(a-min)/180);out.data[i]=160+95*edge;out.data[i+1]=200+55*edge;out.data[i+2]=255;out.data[i+3]=a*(.13+.87*edge);}n.putImageData(out,0,0);}
const neonRebuild=rebuild;rebuild=function(){neonRebuild();if(ready)buildNeon();};
function lightLevel(t){const p=t/(Number($('duration').value)*1000)%1;return p<.035?.65:p<.065?1:p<.09?.72:p<.13?1:.88+.12*Math.sin(p*Math.PI*6)**2;}
const priorFinish=applyFinish;applyFinish=function(t){lightTime=t;priorFinish(t);const s=settings();if(s.finish==='neon'){ac.clearRect(0,0,1024,1024);ac.save();ac.shadowColor=s.color1;ac.shadowBlur=Number(s.glow)*.7;ac.globalAlpha=s.surfaceMotion==='electric'?lightLevel(t):1;ac.drawImage(neonArt,0,0);ac.restore();}if(s.surfaceMotion==='electric'){const phase=t/(Number(s.duration)*1000)%1;ac.save();ac.globalCompositeOperation='source-atop';const x=phase*1500-250,g=ac.createLinearGradient(x-85,0,x+85,0);g.addColorStop(0,'#ffffff00');g.addColorStop(.5,'#ffffffdd');g.addColorStop(1,'#ffffff00');ac.fillStyle=g;ac.fillRect(0,0,1024,1024);ac.restore();}};
const priorText=textLayer;textLayer=function(c,w,h,s){if(s.textFinish!=='neon')return priorText(c,w,h,s);const size=Math.min(w,h)*Number(s.textSize)/100,x=w*Number(s.textX)/100,y=h*Number(s.textY)/100,align=s.layout==='left'?'left':s.layout==='right'?'right':'center';const maxWidth=Math.max(20,align==='left'?w-x-w*.04:align==='right'?x-w*.04:Math.min(x,w-x)*1.9);c.save();c.font='italic 900 '+size+'px Arial,sans-serif';c.textAlign=align;c.lineJoin='round';c.globalAlpha=s.surfaceMotion==='electric'?lightLevel(lightTime):1;c.shadowColor=s.color1;c.shadowBlur=size*.2;c.strokeStyle=s.color1;c.lineWidth=Math.max(1,size*.025);c.strokeText(s.caption,x,y,maxWidth);c.strokeStyle='#e6f4ff';c.lineWidth=Math.max(.5,size*.009);c.strokeText(s.caption,x,y,maxWidth);c.shadowBlur=0;const g=c.createLinearGradient(0,y-size,0,y);g.addColorStop(0,'#273749');g.addColorStop(.5,'#060a11');g.addColorStop(1,'#253346');c.fillStyle=g;c.fillText(s.caption,x,y,maxWidth);c.font='400 '+size*.43+'px Arial,sans-serif';c.fillStyle=s.textcolor;if(s.subtitle)c.fillText(s.subtitle,x,y+size*.85,maxWidth);c.restore();};
const priorNeonSVG=buildSVG;buildSVG=function(){const electric=$('surfaceMotion').value==='electric';if(!electric)return priorNeonSVG();$('surfaceMotion').value='shine';let svg;try{svg=priorNeonSVG();}finally{$('surfaceMotion').value='electric';}const flicker='<animate attributeName="opacity" values="1;.65;1;.72;1;.9;1" keyTimes="0;.035;.065;.09;.13;.65;1" dur="'+$('duration').value+'s" repeatCount="indefinite"/>';svg=svg.replace(/(<image filter="url\(#surface\)"[^>]+)\/>/,'$1>'+flicker+'</image>');if($('textFinish').value==='neon'){// Text is the third full-canvas image; images in the logo use x/y attributes.
let full=0;svg=svg.replace(/<image width="[^>]+\/>/g,match=>{full++;return full===2?'<g>'+flicker+match+'</g>':match;});}return svg;};
$('neonPreset').onclick=()=>{$('finish').value='neon';$('color1').value='#64adff';$('glow').value='18';$('gloss').value='90';$('surfaceMotion').value='electric';$('textFinish').value='neon';$('background').value='color';$('bgcolor').value='#080a0f';$('textcolor').value='#ddebff';$('motion').value='none';rebuild();status('Electric neon applied: glowing edges, light flicker and a shine sweep. Add a caption for neon lettering.');};
if(ready)rebuild();
